name: build mac os
on: [push]
jobs:
  build:
    name: Build MacOS
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: "3.18.x"

      - name: Use cmake
        run: cmake --version

      - name: build
        run: cmake .
        working-directory: src/

      - name: make
        run: make
        working-directory: src/

      - uses: actions/upload-artifact@v2
        with:
          name: Swamp Unpack MacOS
          path: |
            src/libswamp-unpack.a
